---
title: "Aiming Evokes Explicit Motor Adaptation"
output: html_notebook
---

In this document we pre-process and analyze data and make figures for a project where we tested our hypothesis that adding an aiming task to adaptation makes adaptation more explicit. The idea was that asking participants to think really hard on where they would move their hand relative to the target, might cue them in on the fact that aiming your hand somewhere other than the target mighth be the way to optimally do the task. In effect, this would act like instructions such as used in other studies [@Werner2015; @Modchalingam2019]. While aiming is still interesting for measuring explicit learning it is also affecting what is learned, so it should be used only when no other option is available and even then with caution.

The data for this project is available from OSF.

This RStudio Project uses `renv` in an attempt to make sure the same (versions of) packages are used here as we used when we originally wrote the scripts. This probably took some time when starting this up. It also means that all those packages are installed in the project folder, so after being done with the project, you might want to free up some disk space by removing it.

Then we access all our custom functions:

```{r}
# this is for getting the data from OSF:
source('R/data.R')

# this is for (pre)processing the raw data:
source('R/process.R')

# this function provides access to demographics about the participants:
source('R/participants.R')

# here we set the colors and other style elements to be used in plots:
source('R/style.R')

# this has functions to make figures:
source('R/figures.R')

# this file has functions that reproduce the statistical analyses:
source('R/statistics.R')
```

